/**
 * Main.java - Entry point demonstrating the system in action.
 *
 * This file shows how the God Class (OrderManager) is used.
 * Notice how OrderManager's public fields are accessed directly,
 * exposing internal state (Information Hiding violation).
 *
 * DESIGN ISSUES VISIBLE HERE:
 * - Information Hiding: OrderManager fields set directly (no encapsulation)
 * - God Class usage: one object handles everything
 * - Inline Variable: several variables below are used only once
 */
public class Main {

    public static void main(String[] args) {

        // ===== SETUP: God Class takes on all responsibilities =====
        OrderManager manager = new OrderManager();

        // Information Hiding Issue: directly setting public fields instead of
        // using a constructor or setter methods
        manager.customerName = "Alice Johnson";
        manager.customerEmail = "alice@example.com";
        manager.customerAddress = "123 Elm Street, Dhaka";
        manager.customerAge = 67;                  // senior customer
        manager.customerLoyaltyPoints = 850.0;     // silver-tier loyalty

        // Modularity Issue: inventory managed by the same God Class as orders
        manager.addProduct("Laptop", 999.99, 50);
        manager.addProduct("Mouse", 29.99, 200);
        manager.addProduct("Keyboard", 59.99, 150);

        System.out.println("===== ORDER PROCESSING DEMO =====\n");

        // ---------------------------------------------------------------
        // INLINE VARIABLE ISSUE: laptopIndex is used only once immediately.
        // Refactoring: "inline variable" → use 0 directly in the call
        // ---------------------------------------------------------------
        int laptopIndex = 0;
        manager.placeOrder(laptopIndex, 2);

        System.out.println();

        // ---------------------------------------------------------------
        // INLINE VARIABLE ISSUE: mouseIndex and bulkQty used only once.
        // Refactoring: "inline variable" → manager.placeOrder(1, 15)
        // ---------------------------------------------------------------
        int mouseIndex = 1;
        int bulkQty = 15;
        manager.placeOrder(mouseIndex, bulkQty);

        System.out.println();

        // ---------------------------------------------------------------
        // INLINE METHOD ISSUE: getCustomerStatus() is trivial (1 line).
        // Refactoring: "inline method" → replace with the ternary directly
        // ---------------------------------------------------------------
        String status = manager.getCustomerStatus();
        System.out.println("Customer tier: " + status);

        System.out.println();

        // ---------------------------------------------------------------
        // MODULARITY ISSUE: report generated by OrderManager itself instead
        // of a dedicated ReportService class.
        // Refactoring: "extract class" → ReportService
        //              "move method" → move generateReport() there
        // ---------------------------------------------------------------
        manager.generateReport();

        System.out.println("\n===== CUSTOMER OBJECT DEMO =====\n");

        // Customer class demo - showing the thin anemic model
        Customer customer = new Customer("Bob Smith", "bob@example.com", "456 Oak Ave", 22);
        customer.addLoyaltyPoints(250.0);
        customer.updateMembershipTier();

        // Information Hiding Issue: accessing public fields directly
        System.out.println("Name: " + customer.name);
        System.out.println("Email: " + customer.email);
        System.out.println("Tier: " + customer.membershipTier);
        System.out.println("Greeting: " + customer.getGreeting());

        System.out.println("\n===== STOCK CHECK DEMO =====\n");

        // ---------------------------------------------------------------
        // INLINE VARIABLE ISSUE: 'available' is a one-use variable.
        // Refactoring: "inline variable" → use checkStock() directly in if
        // ---------------------------------------------------------------
        boolean available = manager.checkStock(2, 10);
        if (available) {
            System.out.println("Keyboards in stock - placing order.");
            manager.placeOrder(2, 10);
        }
    }
}
